- hosts: all
  gather_facts: true
  vars:
    - ansible_user: centos
    - masternode_public_dns: "{{ masternode_public_dns }}"
    - masternode_private_dns: "{{ masternode_private_dns }}"
    - workernodes_private_dns: "{{ workernodes_private_dns }}"
  tasks:
    - name: get deploy script
      get_url:
        url: https://github.com/karthick-kk/ansible/raw/master/deployokd311.sh
        dest: /home/centos/deployokd311.sh
        mode: '0755'
    - name: run deploy script
      shell: ./deployokd311.sh --masternode_public_dns '"{{ masternode_public_dns }}"' --masternode_private_dns '"{{ masternode_private_dns }}"' --workernodes_private_dns '"{{ workernodes_private_dns }}"'
