- hosts: all
  gather_facts: false
  vars:
    - ansible_user: ubuntu
#    - ansible_ssh_private_key_file: /home/karthickk/Downloads/testvmec2.pem
  tasks:
    - name: test play
      debug: msg="Iam {{ ansible_user }} on {{ ansible_host }}"
  
